version: '3.8'

services:
  # ---------------------------------
  # FRONTEND (z.B. Streamlit)
  # ---------------------------------
  frontend:
    image: mlops25acrdev.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - API_URL=http://backend:8000/predict

  # ---------------------------------
  # BACKEND (z.B. FastAPI)
  # ---------------------------------
  backend:
    image: mlops25acrdev.azurecr.io/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    networks:
      - app_network
    # Beispiel-ENV-Variablen, falls nötig
    environment:
      MLFLOW_SERVING_URI: http://mlflow:8080

  # ---------------------------------
  # MLFLOW SERVER
  # ---------------------------------
  mlflow:
    image: mlops25acrdev.azurecr.io/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - mlflow_artifacts:/mlflow
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow

 # ---------------------------------
  # MODEL SERVICE
  # ---------------------------------
  # model_service:
  #   image: income_predictor:latest  # Use the image built by MLflow
  #   container_name: model_service
  #   ports:
  #     - "8080:8080"  # MLServer default port
  #   networks:
  #     - app_network
  #   volumes:
  #     - model_data:/opt/ml/model  # Optional volume for model data
  #   environment:
  #     MLSERVER_MODEL_NAME: income_predictor
  #     MLSERVER_HTTP_PORT: 8080

  # ---------------------------------
  # MONITORING (z.B. Grafana als Beispiel)
  # # ---------------------------------
  monitoring:
    image: mlops25acrdev.azurecr.io/monitoring:latest
    container_name: monitoring
    ports:
      - "3000:3000"  # Standard-Grafana-Port
    networks:
      - app_network
    depends_on:
      - backend
      - mlflow

# ---------------------------------
# NETWORKS & VOLUMES
# ---------------------------------
networks:
  app_network:
    driver: bridge

volumes:
  mlflow_artifacts: