global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend-app.azurewebsites.net']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend-app.azurewebsites.net']
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow-app.azurewebsites.net']

remote_write:
  - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    basic_auth:
      username: "GRAFANA_CLOUD_USER"
      password: "GRAFANA_CLOUD_API_KEY"
