{
 "title": "MLOps Monitoring Dashboard",
 "tags": [
  "mlops",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Frontend Usage (5m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(frontend_page_views_total[5m])",
     "legendFormat": "Page Views"
    },
    {
     "expr": "rate(frontend_predictions_total[5m])",
     "legendFormat": "Predictions"
    }
   ]
  },
  {
   "title": "Services Status",
   "type": "stat",
   "description": "Status of services",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frontend_up", "legendFormat": "Frontend" },
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "Backend"
    },
    { "expr": "model_service_up", "legendFormat": "Model Service" }
   ]
  },
  {
   "title": "Frontend Usage (Totals)",
   "type": "bargauge",
   "description": "Total Frontend Metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frontend_page_views_total", "legendFormat": "Page Views" },
    { "expr": "frontend_predictions_total", "legendFormat": "Predictions" }
   ]
  },
  {
   "title": "Model Information",
   "type": "stat",
   "description": "Model Information",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_version", "legendFormat": "Model Version" },
    { "expr": "model_requests_total", "legendFormat": "Model Requests" },
    { "expr": "model_errors_total", "legendFormat": "Model Errors" }
   ]
  }
 ]
}